apiVersion: v2
name: helm
description: Declarative Continuous Compliance for Kubernetes containers
type: application
version: 1.7.0
appVersion: "1.6.0"
keywords:
  - kubernetes
  - forensics
  - compliance
  - checkpoint
  - criu
home: https://github.com/getreeldev/reel
sources:
  - https://github.com/getreeldev/reel
maintainers:
  - name: Reel
    url: https://getreel.dev
