{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "reel.fullname" . }}
  labels:
    {{- include "reel.labels" . | nindent 4 }}
    app.kubernetes.io/component: forensics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "reel.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "reel.serviceAccountName" . }}
  namespace: {{ include "reel.namespace" . }}
{{- end }}
