{{- if and .Values.license.token (not .Values.license.secretRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reel.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reel.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.license.token | b64enc }}
{{- end }}
