{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reel.serviceAccountName" . }}
  namespace: {{ include "reel.namespace" . }}
  labels:
    {{- include "reel.labels" . | nindent 4 }}
    app.kubernetes.io/component: forensics
{{- end }}
